import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/context/query-provider";
import { ConvexProvider } from "@/context/convex-provider";
import CookieConsent from "@/components/cookie-consent";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { ensureUserFromKinde } from "@/lib/billing";
import { ensureUserCredits, syncRealtimeCredits } from "@/lib/credits";
import { DevConsoleBanner } from "@/components/dev-console-banner";

const jostSans = Jost({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "XTool.ai - AI Workspace",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = getKindeServerSession();
  const user = await getUser();

  if (user) {
    await ensureUserFromKinde(user);
    await ensureUserCredits(user.id);
    await syncRealtimeCredits({ kindeId: user.id });
  }
  return (
    <html lang="en">
      <body className={`${jostSans.className} antialiased`}>
        <ConvexProvider>
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
              disableTransitionOnChange
            >
              {children}
              <DevConsoleBanner />
              <CookieConsent />
              <Toaster richColors position="bottom-center" />
            </ThemeProvider>
          </QueryProvider>
        </ConvexProvider>
      </body>
    </html>
  );
}
